// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing Supabase environment variable(s): ${missing.join(', ')}. Local database operations will mock-fail on use.`);
    return new Proxy({} as any, {
      get(target, prop) {
        if (
          typeof prop === 'symbol' ||
          prop === 'then' ||
          prop === '$$typeof' ||
          prop === 'toJSON' ||
          prop === '__esModule' ||
          prop === 'default'
        ) {
          return undefined;
        }
        return () => {
          throw new Error(`Supabase is not configured. Missing environment variable(s): ${missing.join(', ')}`);
        };
      }
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(target, prop, receiver) {
    if (
      typeof prop === 'symbol' ||
      prop === 'then' ||
      prop === '$$typeof' ||
      prop === 'toJSON' ||
      prop === '__esModule' ||
      prop === 'default'
    ) {
      return Reflect.get(target, prop, receiver);
    }
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
